// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: database.proto

package net.swofty.db.proto;

public interface CustomObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CustomObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Add fields for your custom object
   * </pre>
   *
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Add this field to store the serialized Java object
   * </pre>
   *
   * <code>bytes serialized_java_object = 3;</code>
   * @return The serializedJavaObject.
   */
  com.google.protobuf.ByteString getSerializedJavaObject();
}
