// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: database.proto

package net.swofty.db.proto;

public interface DatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Database)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Document documents = 1;</code>
   */
  java.util.List<net.swofty.db.proto.Document> 
      getDocumentsList();
  /**
   * <code>repeated .Document documents = 1;</code>
   */
  net.swofty.db.proto.Document getDocuments(int index);
  /**
   * <code>repeated .Document documents = 1;</code>
   */
  int getDocumentsCount();
  /**
   * <code>repeated .Document documents = 1;</code>
   */
  java.util.List<? extends net.swofty.db.proto.DocumentOrBuilder> 
      getDocumentsOrBuilderList();
  /**
   * <code>repeated .Document documents = 1;</code>
   */
  net.swofty.db.proto.DocumentOrBuilder getDocumentsOrBuilder(
      int index);
}
