// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: database.proto

package net.swofty.db.proto;

public interface DocumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Document)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string document_key = 1;</code>
   * @return The documentKey.
   */
  java.lang.String getDocumentKey();
  /**
   * <code>string document_key = 1;</code>
   * @return The bytes for documentKey.
   */
  com.google.protobuf.ByteString
      getDocumentKeyBytes();

  /**
   * <code>repeated .Entry entries = 2;</code>
   */
  java.util.List<net.swofty.db.proto.Entry> 
      getEntriesList();
  /**
   * <code>repeated .Entry entries = 2;</code>
   */
  net.swofty.db.proto.Entry getEntries(int index);
  /**
   * <code>repeated .Entry entries = 2;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .Entry entries = 2;</code>
   */
  java.util.List<? extends net.swofty.db.proto.EntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .Entry entries = 2;</code>
   */
  net.swofty.db.proto.EntryOrBuilder getEntriesOrBuilder(
      int index);
}
