// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: database.proto

package net.swofty.db.proto;

/**
 * Protobuf type {@code Entry}
 */
public final class Entry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Entry)
    EntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Entry.newBuilder() to construct.
  private Entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Entry() {
    key_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Entry();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.swofty.db.proto.SwoftyDB.internal_static_Entry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.swofty.db.proto.SwoftyDB.internal_static_Entry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.swofty.db.proto.Entry.class, net.swofty.db.proto.Entry.Builder.class);
  }

  private int valueCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    STRING_VALUE(2),
    INT_VALUE(3),
    CUSTOM_OBJECT(4),
    DOUBLE_VALUE(5),
    LONG_VALUE(6),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 2: return STRING_VALUE;
        case 3: return INT_VALUE;
        case 4: return CUSTOM_OBJECT;
        case 5: return DOUBLE_VALUE;
        case 6: return LONG_VALUE;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  public static final int KEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object key_ = "";
  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRING_VALUE_FIELD_NUMBER = 2;
  /**
   * <code>string string_value = 2;</code>
   * @return Whether the stringValue field is set.
   */
  public boolean hasStringValue() {
    return valueCase_ == 2;
  }
  /**
   * <code>string string_value = 2;</code>
   * @return The stringValue.
   */
  public java.lang.String getStringValue() {
    java.lang.Object ref = "";
    if (valueCase_ == 2) {
      ref = value_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (valueCase_ == 2) {
        value_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string string_value = 2;</code>
   * @return The bytes for stringValue.
   */
  public com.google.protobuf.ByteString
      getStringValueBytes() {
    java.lang.Object ref = "";
    if (valueCase_ == 2) {
      ref = value_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (valueCase_ == 2) {
        value_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INT_VALUE_FIELD_NUMBER = 3;
  /**
   * <code>int32 int_value = 3;</code>
   * @return Whether the intValue field is set.
   */
  @java.lang.Override
  public boolean hasIntValue() {
    return valueCase_ == 3;
  }
  /**
   * <code>int32 int_value = 3;</code>
   * @return The intValue.
   */
  @java.lang.Override
  public int getIntValue() {
    if (valueCase_ == 3) {
      return (java.lang.Integer) value_;
    }
    return 0;
  }

  public static final int CUSTOM_OBJECT_FIELD_NUMBER = 4;
  /**
   * <code>.CustomObject custom_object = 4;</code>
   * @return Whether the customObject field is set.
   */
  @java.lang.Override
  public boolean hasCustomObject() {
    return valueCase_ == 4;
  }
  /**
   * <code>.CustomObject custom_object = 4;</code>
   * @return The customObject.
   */
  @java.lang.Override
  public net.swofty.db.proto.CustomObject getCustomObject() {
    if (valueCase_ == 4) {
       return (net.swofty.db.proto.CustomObject) value_;
    }
    return net.swofty.db.proto.CustomObject.getDefaultInstance();
  }
  /**
   * <code>.CustomObject custom_object = 4;</code>
   */
  @java.lang.Override
  public net.swofty.db.proto.CustomObjectOrBuilder getCustomObjectOrBuilder() {
    if (valueCase_ == 4) {
       return (net.swofty.db.proto.CustomObject) value_;
    }
    return net.swofty.db.proto.CustomObject.getDefaultInstance();
  }

  public static final int DOUBLE_VALUE_FIELD_NUMBER = 5;
  /**
   * <code>double double_value = 5;</code>
   * @return Whether the doubleValue field is set.
   */
  @java.lang.Override
  public boolean hasDoubleValue() {
    return valueCase_ == 5;
  }
  /**
   * <code>double double_value = 5;</code>
   * @return The doubleValue.
   */
  @java.lang.Override
  public double getDoubleValue() {
    if (valueCase_ == 5) {
      return (java.lang.Double) value_;
    }
    return 0D;
  }

  public static final int LONG_VALUE_FIELD_NUMBER = 6;
  /**
   * <code>int64 long_value = 6;</code>
   * @return Whether the longValue field is set.
   */
  @java.lang.Override
  public boolean hasLongValue() {
    return valueCase_ == 6;
  }
  /**
   * <code>int64 long_value = 6;</code>
   * @return The longValue.
   */
  @java.lang.Override
  public long getLongValue() {
    if (valueCase_ == 6) {
      return (java.lang.Long) value_;
    }
    return 0L;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
    }
    if (valueCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
    }
    if (valueCase_ == 3) {
      output.writeInt32(
          3, (int)((java.lang.Integer) value_));
    }
    if (valueCase_ == 4) {
      output.writeMessage(4, (net.swofty.db.proto.CustomObject) value_);
    }
    if (valueCase_ == 5) {
      output.writeDouble(
          5, (double)((java.lang.Double) value_));
    }
    if (valueCase_ == 6) {
      output.writeInt64(
          6, (long)((java.lang.Long) value_));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
    }
    if (valueCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
    }
    if (valueCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            3, (int)((java.lang.Integer) value_));
    }
    if (valueCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (net.swofty.db.proto.CustomObject) value_);
    }
    if (valueCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(
            5, (double)((java.lang.Double) value_));
    }
    if (valueCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            6, (long)((java.lang.Long) value_));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.swofty.db.proto.Entry)) {
      return super.equals(obj);
    }
    net.swofty.db.proto.Entry other = (net.swofty.db.proto.Entry) obj;

    if (!getKey()
        .equals(other.getKey())) return false;
    if (!getValueCase().equals(other.getValueCase())) return false;
    switch (valueCase_) {
      case 2:
        if (!getStringValue()
            .equals(other.getStringValue())) return false;
        break;
      case 3:
        if (getIntValue()
            != other.getIntValue()) return false;
        break;
      case 4:
        if (!getCustomObject()
            .equals(other.getCustomObject())) return false;
        break;
      case 5:
        if (java.lang.Double.doubleToLongBits(getDoubleValue())
            != java.lang.Double.doubleToLongBits(
                other.getDoubleValue())) return false;
        break;
      case 6:
        if (getLongValue()
            != other.getLongValue()) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    switch (valueCase_) {
      case 2:
        hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStringValue().hashCode();
        break;
      case 3:
        hash = (37 * hash) + INT_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getIntValue();
        break;
      case 4:
        hash = (37 * hash) + CUSTOM_OBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getCustomObject().hashCode();
        break;
      case 5:
        hash = (37 * hash) + DOUBLE_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDoubleValue()));
        break;
      case 6:
        hash = (37 * hash) + LONG_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLongValue());
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.swofty.db.proto.Entry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.swofty.db.proto.Entry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.swofty.db.proto.Entry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.swofty.db.proto.Entry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.swofty.db.proto.Entry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.swofty.db.proto.Entry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.swofty.db.proto.Entry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.swofty.db.proto.Entry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.swofty.db.proto.Entry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.swofty.db.proto.Entry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.swofty.db.proto.Entry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.swofty.db.proto.Entry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.swofty.db.proto.Entry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Entry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Entry)
      net.swofty.db.proto.EntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.swofty.db.proto.SwoftyDB.internal_static_Entry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.swofty.db.proto.SwoftyDB.internal_static_Entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.swofty.db.proto.Entry.class, net.swofty.db.proto.Entry.Builder.class);
    }

    // Construct using net.swofty.db.proto.Entry.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      key_ = "";
      if (customObjectBuilder_ != null) {
        customObjectBuilder_.clear();
      }
      valueCase_ = 0;
      value_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.swofty.db.proto.SwoftyDB.internal_static_Entry_descriptor;
    }

    @java.lang.Override
    public net.swofty.db.proto.Entry getDefaultInstanceForType() {
      return net.swofty.db.proto.Entry.getDefaultInstance();
    }

    @java.lang.Override
    public net.swofty.db.proto.Entry build() {
      net.swofty.db.proto.Entry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.swofty.db.proto.Entry buildPartial() {
      net.swofty.db.proto.Entry result = new net.swofty.db.proto.Entry(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(net.swofty.db.proto.Entry result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.key_ = key_;
      }
    }

    private void buildPartialOneofs(net.swofty.db.proto.Entry result) {
      result.valueCase_ = valueCase_;
      result.value_ = this.value_;
      if (valueCase_ == 4 &&
          customObjectBuilder_ != null) {
        result.value_ = customObjectBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.swofty.db.proto.Entry) {
        return mergeFrom((net.swofty.db.proto.Entry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.swofty.db.proto.Entry other) {
      if (other == net.swofty.db.proto.Entry.getDefaultInstance()) return this;
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      switch (other.getValueCase()) {
        case STRING_VALUE: {
          valueCase_ = 2;
          value_ = other.value_;
          onChanged();
          break;
        }
        case INT_VALUE: {
          setIntValue(other.getIntValue());
          break;
        }
        case CUSTOM_OBJECT: {
          mergeCustomObject(other.getCustomObject());
          break;
        }
        case DOUBLE_VALUE: {
          setDoubleValue(other.getDoubleValue());
          break;
        }
        case LONG_VALUE: {
          setLongValue(other.getLongValue());
          break;
        }
        case VALUE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              key_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              valueCase_ = 2;
              value_ = s;
              break;
            } // case 18
            case 24: {
              value_ = input.readInt32();
              valueCase_ = 3;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getCustomObjectFieldBuilder().getBuilder(),
                  extensionRegistry);
              valueCase_ = 4;
              break;
            } // case 34
            case 41: {
              value_ = input.readDouble();
              valueCase_ = 5;
              break;
            } // case 41
            case 48: {
              value_ = input.readInt64();
              valueCase_ = 6;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public ValueCase
        getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public Builder clearValue() {
      valueCase_ = 0;
      value_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object key_ = "";
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      key_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      key_ = getDefaultInstance().getKey();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string key = 1;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      key_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     * <code>string string_value = 2;</code>
     * @return Whether the stringValue field is set.
     */
    @java.lang.Override
    public boolean hasStringValue() {
      return valueCase_ == 2;
    }
    /**
     * <code>string string_value = 2;</code>
     * @return The stringValue.
     */
    @java.lang.Override
    public java.lang.String getStringValue() {
      java.lang.Object ref = "";
      if (valueCase_ == 2) {
        ref = value_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 2) {
          value_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string_value = 2;</code>
     * @return The bytes for stringValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 2) {
        ref = value_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 2) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string_value = 2;</code>
     * @param value The stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValue(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      valueCase_ = 2;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string string_value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringValue() {
      if (valueCase_ == 2) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string string_value = 2;</code>
     * @param value The bytes for stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      valueCase_ = 2;
      value_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 int_value = 3;</code>
     * @return Whether the intValue field is set.
     */
    public boolean hasIntValue() {
      return valueCase_ == 3;
    }
    /**
     * <code>int32 int_value = 3;</code>
     * @return The intValue.
     */
    public int getIntValue() {
      if (valueCase_ == 3) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }
    /**
     * <code>int32 int_value = 3;</code>
     * @param value The intValue to set.
     * @return This builder for chaining.
     */
    public Builder setIntValue(int value) {

      valueCase_ = 3;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 int_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntValue() {
      if (valueCase_ == 3) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        net.swofty.db.proto.CustomObject, net.swofty.db.proto.CustomObject.Builder, net.swofty.db.proto.CustomObjectOrBuilder> customObjectBuilder_;
    /**
     * <code>.CustomObject custom_object = 4;</code>
     * @return Whether the customObject field is set.
     */
    @java.lang.Override
    public boolean hasCustomObject() {
      return valueCase_ == 4;
    }
    /**
     * <code>.CustomObject custom_object = 4;</code>
     * @return The customObject.
     */
    @java.lang.Override
    public net.swofty.db.proto.CustomObject getCustomObject() {
      if (customObjectBuilder_ == null) {
        if (valueCase_ == 4) {
          return (net.swofty.db.proto.CustomObject) value_;
        }
        return net.swofty.db.proto.CustomObject.getDefaultInstance();
      } else {
        if (valueCase_ == 4) {
          return customObjectBuilder_.getMessage();
        }
        return net.swofty.db.proto.CustomObject.getDefaultInstance();
      }
    }
    /**
     * <code>.CustomObject custom_object = 4;</code>
     */
    public Builder setCustomObject(net.swofty.db.proto.CustomObject value) {
      if (customObjectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        customObjectBuilder_.setMessage(value);
      }
      valueCase_ = 4;
      return this;
    }
    /**
     * <code>.CustomObject custom_object = 4;</code>
     */
    public Builder setCustomObject(
        net.swofty.db.proto.CustomObject.Builder builderForValue) {
      if (customObjectBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        customObjectBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 4;
      return this;
    }
    /**
     * <code>.CustomObject custom_object = 4;</code>
     */
    public Builder mergeCustomObject(net.swofty.db.proto.CustomObject value) {
      if (customObjectBuilder_ == null) {
        if (valueCase_ == 4 &&
            value_ != net.swofty.db.proto.CustomObject.getDefaultInstance()) {
          value_ = net.swofty.db.proto.CustomObject.newBuilder((net.swofty.db.proto.CustomObject) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 4) {
          customObjectBuilder_.mergeFrom(value);
        } else {
          customObjectBuilder_.setMessage(value);
        }
      }
      valueCase_ = 4;
      return this;
    }
    /**
     * <code>.CustomObject custom_object = 4;</code>
     */
    public Builder clearCustomObject() {
      if (customObjectBuilder_ == null) {
        if (valueCase_ == 4) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 4) {
          valueCase_ = 0;
          value_ = null;
        }
        customObjectBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.CustomObject custom_object = 4;</code>
     */
    public net.swofty.db.proto.CustomObject.Builder getCustomObjectBuilder() {
      return getCustomObjectFieldBuilder().getBuilder();
    }
    /**
     * <code>.CustomObject custom_object = 4;</code>
     */
    @java.lang.Override
    public net.swofty.db.proto.CustomObjectOrBuilder getCustomObjectOrBuilder() {
      if ((valueCase_ == 4) && (customObjectBuilder_ != null)) {
        return customObjectBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 4) {
          return (net.swofty.db.proto.CustomObject) value_;
        }
        return net.swofty.db.proto.CustomObject.getDefaultInstance();
      }
    }
    /**
     * <code>.CustomObject custom_object = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        net.swofty.db.proto.CustomObject, net.swofty.db.proto.CustomObject.Builder, net.swofty.db.proto.CustomObjectOrBuilder> 
        getCustomObjectFieldBuilder() {
      if (customObjectBuilder_ == null) {
        if (!(valueCase_ == 4)) {
          value_ = net.swofty.db.proto.CustomObject.getDefaultInstance();
        }
        customObjectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            net.swofty.db.proto.CustomObject, net.swofty.db.proto.CustomObject.Builder, net.swofty.db.proto.CustomObjectOrBuilder>(
                (net.swofty.db.proto.CustomObject) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 4;
      onChanged();
      return customObjectBuilder_;
    }

    /**
     * <code>double double_value = 5;</code>
     * @return Whether the doubleValue field is set.
     */
    public boolean hasDoubleValue() {
      return valueCase_ == 5;
    }
    /**
     * <code>double double_value = 5;</code>
     * @return The doubleValue.
     */
    public double getDoubleValue() {
      if (valueCase_ == 5) {
        return (java.lang.Double) value_;
      }
      return 0D;
    }
    /**
     * <code>double double_value = 5;</code>
     * @param value The doubleValue to set.
     * @return This builder for chaining.
     */
    public Builder setDoubleValue(double value) {

      valueCase_ = 5;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double double_value = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDoubleValue() {
      if (valueCase_ == 5) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>int64 long_value = 6;</code>
     * @return Whether the longValue field is set.
     */
    public boolean hasLongValue() {
      return valueCase_ == 6;
    }
    /**
     * <code>int64 long_value = 6;</code>
     * @return The longValue.
     */
    public long getLongValue() {
      if (valueCase_ == 6) {
        return (java.lang.Long) value_;
      }
      return 0L;
    }
    /**
     * <code>int64 long_value = 6;</code>
     * @param value The longValue to set.
     * @return This builder for chaining.
     */
    public Builder setLongValue(long value) {

      valueCase_ = 6;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 long_value = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLongValue() {
      if (valueCase_ == 6) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Entry)
  }

  // @@protoc_insertion_point(class_scope:Entry)
  private static final net.swofty.db.proto.Entry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.swofty.db.proto.Entry();
  }

  public static net.swofty.db.proto.Entry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Entry>
      PARSER = new com.google.protobuf.AbstractParser<Entry>() {
    @java.lang.Override
    public Entry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Entry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Entry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.swofty.db.proto.Entry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

