// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: database.proto

package net.swofty.db.proto;

public final class SwoftyDB {
  private SwoftyDB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomObject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValueWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValueWrapper_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Document_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Document_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Database_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Database_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016database.proto\"H\n\014CustomObject\022\n\n\002id\030\001" +
      " \001(\005\022\014\n\004name\030\002 \001(\t\022\036\n\026serialized_java_ob" +
      "ject\030\003 \001(\014\"\240\001\n\005Entry\022\013\n\003key\030\001 \001(\t\022\026\n\014str" +
      "ing_value\030\002 \001(\tH\000\022\023\n\tint_value\030\003 \001(\005H\000\022&" +
      "\n\rcustom_object\030\004 \001(\0132\r.CustomObjectH\000\022\026" +
      "\n\014double_value\030\005 \001(\001H\000\022\024\n\nlong_value\030\006 \001" +
      "(\003H\000B\007\n\005value\"\232\001\n\014ValueWrapper\022\026\n\014string" +
      "_value\030\001 \001(\tH\000\022\023\n\tint_value\030\002 \001(\005H\000\022&\n\rc" +
      "ustom_object\030\003 \001(\0132\r.CustomObjectH\000\022\026\n\014d" +
      "ouble_value\030\004 \001(\001H\000\022\024\n\nlong_value\030\005 \001(\003H" +
      "\000B\007\n\005value\"9\n\010Document\022\024\n\014document_key\030\001" +
      " \001(\t\022\027\n\007entries\030\002 \003(\0132\006.Entry\"(\n\010Databas" +
      "e\022\034\n\tdocuments\030\001 \003(\0132\t.DocumentB!\n\023net.s" +
      "wofty.db.protoB\010SwoftyDBP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CustomObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CustomObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomObject_descriptor,
        new java.lang.String[] { "Id", "Name", "SerializedJavaObject", });
    internal_static_Entry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Entry_descriptor,
        new java.lang.String[] { "Key", "StringValue", "IntValue", "CustomObject", "DoubleValue", "LongValue", "Value", });
    internal_static_ValueWrapper_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ValueWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValueWrapper_descriptor,
        new java.lang.String[] { "StringValue", "IntValue", "CustomObject", "DoubleValue", "LongValue", "Value", });
    internal_static_Document_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Document_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Document_descriptor,
        new java.lang.String[] { "DocumentKey", "Entries", });
    internal_static_Database_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Database_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Database_descriptor,
        new java.lang.String[] { "Documents", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
