// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: database.proto

package net.swofty.db.proto;

public interface ValueWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ValueWrapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string string_value = 1;</code>
   * @return Whether the stringValue field is set.
   */
  boolean hasStringValue();
  /**
   * <code>string string_value = 1;</code>
   * @return The stringValue.
   */
  java.lang.String getStringValue();
  /**
   * <code>string string_value = 1;</code>
   * @return The bytes for stringValue.
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>int32 int_value = 2;</code>
   * @return Whether the intValue field is set.
   */
  boolean hasIntValue();
  /**
   * <code>int32 int_value = 2;</code>
   * @return The intValue.
   */
  int getIntValue();

  /**
   * <code>.CustomObject custom_object = 3;</code>
   * @return Whether the customObject field is set.
   */
  boolean hasCustomObject();
  /**
   * <code>.CustomObject custom_object = 3;</code>
   * @return The customObject.
   */
  net.swofty.db.proto.CustomObject getCustomObject();
  /**
   * <code>.CustomObject custom_object = 3;</code>
   */
  net.swofty.db.proto.CustomObjectOrBuilder getCustomObjectOrBuilder();

  /**
   * <code>double double_value = 4;</code>
   * @return Whether the doubleValue field is set.
   */
  boolean hasDoubleValue();
  /**
   * <code>double double_value = 4;</code>
   * @return The doubleValue.
   */
  double getDoubleValue();

  /**
   * <code>int64 long_value = 5;</code>
   * @return Whether the longValue field is set.
   */
  boolean hasLongValue();
  /**
   * <code>int64 long_value = 5;</code>
   * @return The longValue.
   */
  long getLongValue();

  net.swofty.db.proto.ValueWrapper.ValueCase getValueCase();
}
